### ISSUE TITLE
Production-readiness

### ISSUE THREAD

**Issue by mwgamble** [reverbc/pylint-pytest#3]
If the current state of this project is without any known bugs, it would be worth tagging a `1.0.0` release and removing the beta label. This will help improve adoption.

**Comment by reverbc** [comment]
Thanks for the suggestion! It's been a while since the last time I worked on this project but I'll come back to it and consider if it's mature enough to call `1.0.0`

**Comment by reverbc** [comment]
`1.0.0` is out 🎉
https://pypi.org/project/pylint-pytest/1.0.0/
